# We want to extend the FillPDF Settings configuration
fillpdf.settings:
  type: config_object
  mapping:
    backend:
      type: string
      label: 'PDF processing method'
    fillpdf_rest_endpoint:
      type: string
      label: 'FillPDF Docker PDFTK REST endpoint'
    fillpdf_rest_protocol:
      type: string
      label: 'FillPDF Docker PDFTK REST protocol'
